import {
    ImageIcon,
    FileText,
    FileCode,
    FileJson,
    Package,
    Music,
    Video,
    Settings,
    Database,
    Archive,
    GitBranch,
    File,
    Folder,
    Terminal,
    Lock,
    Globe,
    BookOpen,
    BarChart,
    Presentation,
    Cpu,
    Palette,
    Cloud,
    Shield,
    Key,
    MessageSquare,
    Image,
    Film,
    Headphones,
    FileArchive,
    Book,
    Type,
    Mail,
    Calendar,
    Users,
    Map,
    Code,
    Server,
    DatabaseBackup,
    FileSpreadsheet,
    FileSignature,
    FileAudio,
    FileVideo,
    FileImage,
    FileType,
    FileOutput,
    FileInput,
    Binary,
    CircuitBoard,
    Atom,
    FlaskConical,
    TestTube,
    Beaker,
    Telescope,
    Rocket,
    Ship,
    Car,
    Building,
    Leaf,
    Droplets,
    Zap,
    Battery,
    Cctv,
    HardDrive,
    Router,
    Network,
    Wifi,
    Bluetooth,
    Radio,
    Satellite,
    Smartphone,
    Monitor,
    Printer,
    Camera,
    Mic,
    Gamepad2,
    Music2,
    Tv,
    RadioTower,
    Box,
} from "lucide-react"

import type { FileIcon } from "@/types/index"

// File Icons - Enhanced with comprehensive coverage
export const FILE_ICONS: Record<string, FileIcon> = {
    // ========== IMAGES ==========
    png: { icon: ImageIcon, color: "text-blue-500" },
    jpg: { icon: ImageIcon, color: "text-blue-500" },
    jpeg: { icon: ImageIcon, color: "text-blue-500" },
    gif: { icon: ImageIcon, color: "text-pink-500" },
    svg: { icon: Image, color: "text-orange-500" },
    webp: { icon: ImageIcon, color: "text-blue-400" },
    heic: { icon: ImageIcon, color: "text-purple-500" },
    heif: { icon: ImageIcon, color: "text-purple-500" },
    bmp: { icon: ImageIcon, color: "text-gray-600" },
    tiff: { icon: ImageIcon, color: "text-gray-600" },
    tif: { icon: ImageIcon, color: "text-gray-600" },
    ico: { icon: ImageIcon, color: "text-yellow-500" },
    icns: { icon: ImageIcon, color: "text-yellow-500" },
    psd: { icon: ImageIcon, color: "text-blue-600" },
    ai: { icon: ImageIcon, color: "text-orange-600" },
    eps: { icon: ImageIcon, color: "text-purple-600" },
    raw: { icon: ImageIcon, color: "text-gray-700" },
    cr2: { icon: ImageIcon, color: "text-gray-700" },
    nef: { icon: ImageIcon, color: "text-gray-700" },
    arw: { icon: ImageIcon, color: "text-gray-700" },

    // ========== DOCUMENTS ==========
    // Office Documents
    pdf: { icon: FileText, color: "text-red-500" },
    doc: { icon: FileText, color: "text-blue-600" },
    docx: { icon: FileText, color: "text-blue-600" },
    docm: { icon: FileText, color: "text-blue-600" },
    dot: { icon: FileText, color: "text-blue-600" },
    dotx: { icon: FileText, color: "text-blue-600" },
    
    // Spreadsheets
    xlsx: { icon: FileSpreadsheet, color: "text-green-500" },
    xls: { icon: FileSpreadsheet, color: "text-green-500" },
    xlsm: { icon: FileSpreadsheet, color: "text-green-500" },
    xlsb: { icon: FileSpreadsheet, color: "text-green-500" },
    csv: { icon: FileSpreadsheet, color: "text-green-600" },
    tsv: { icon: FileSpreadsheet, color: "text-green-600" },
    ods: { icon: FileSpreadsheet, color: "text-green-400" },
    
    // Presentations
    pptx: { icon: Presentation, color: "text-orange-500" },
    ppt: { icon: Presentation, color: "text-orange-500" },
    pptm: { icon: Presentation, color: "text-orange-500" },
    potx: { icon: Presentation, color: "text-orange-500" },
    ppsx: { icon: Presentation, color: "text-orange-600" },
    pps: { icon: Presentation, color: "text-orange-600" },
    odp: { icon: Presentation, color: "text-orange-400" },
    
    // Text & Markup
    txt: { icon: FileText, color: "text-gray-600" },
    md: { icon: BookOpen, color: "text-gray-600" },
    rtf: { icon: FileText, color: "text-blue-500" },
    tex: { icon: Type, color: "text-gray-700" },
    epub: { icon: Book, color: "text-purple-500" },
    mobi: { icon: Book, color: "text-orange-500" },
    azw3: { icon: Book, color: "text-blue-500" },

    // ========== CODE & DEVELOPMENT ==========
    // Web
    js: { icon: FileCode, color: "text-yellow-500" },
    jsx: { icon: FileCode, color: "text-blue-500" },
    ts: { icon: FileCode, color: "text-blue-600" },
    tsx: { icon: FileCode, color: "text-blue-600" },
    html: { icon: FileCode, color: "text-orange-500" },
    htm: { icon: FileCode, color: "text-orange-500" },
    css: { icon: FileCode, color: "text-blue-400" },
    scss: { icon: FileCode, color: "text-pink-500" },
    sass: { icon: FileCode, color: "text-pink-600" },
    less: { icon: FileCode, color: "text-blue-300" },
    
    // Config & Data
    json: { icon: FileJson, color: "text-yellow-600" },
    yaml: { icon: FileJson, color: "text-red-400" },
    yml: { icon: FileJson, color: "text-red-400" },
    toml: { icon: FileJson, color: "text-gray-600" },
    xml: { icon: FileCode, color: "text-orange-600" },
    
    // Programming Languages
    py: { icon: FileCode, color: "text-green-500" },
    pyc: { icon: FileCode, color: "text-green-600" },
    pyo: { icon: FileCode, color: "text-green-600" },
    cpp: { icon: FileCode, color: "text-blue-500" },
    cc: { icon: FileCode, color: "text-blue-500" },
    cxx: { icon: FileCode, color: "text-blue-500" },
    c: { icon: FileCode, color: "text-gray-600" },
    h: { icon: FileCode, color: "text-purple-500" },
    hpp: { icon: FileCode, color: "text-purple-500" },
    java: { icon: FileCode, color: "text-red-500" },
    class: { icon: FileCode, color: "text-red-600" },
    jar: { icon: Package, color: "text-red-500" },
    kotlin: { icon: FileCode, color: "text-purple-500" },
    kt: { icon: FileCode, color: "text-purple-500" },
    swift: { icon: FileCode, color: "text-orange-500" },
    go: { icon: FileCode, color: "text-blue-500" },
    rs: { icon: FileCode, color: "text-orange-600" },
    php: { icon: FileCode, color: "text-purple-500" },
    rb: { icon: FileCode, color: "text-red-500" },
    perl: { icon: FileCode, color: "text-blue-400" },
    pl: { icon: FileCode, color: "text-blue-400" },
    scala: { icon: FileCode, color: "text-red-500" },
    sc: { icon: FileCode, color: "text-red-500" },
    dart: { icon: FileCode, color: "text-blue-500" },
    cs: { icon: FileCode, color: "text-green-600" },
    csproj: { icon: FileCode, color: "text-green-600" },
    sln: { icon: FileCode, color: "text-blue-600" },
    vb: { icon: FileCode, color: "text-blue-500" },
    vbs: { icon: FileCode, color: "text-blue-500" },
    lua: { icon: FileCode, color: "text-blue-700" },
    sql: { icon: Database, color: "text-blue-500" },
    plsql: { icon: Database, color: "text-blue-600" },
    tsql: { icon: Database, color: "text-blue-600" },
    
    // Shell & Scripts
    sh: { icon: Terminal, color: "text-green-500" },
    bash: { icon: Terminal, color: "text-green-500" },
    zsh: { icon: Terminal, color: "text-green-600" },
    fish: { icon: Terminal, color: "text-blue-500" },
    ps1: { icon: Terminal, color: "text-blue-600" },
    bat: { icon: Terminal, color: "text-gray-600" },
    cmd: { icon: Terminal, color: "text-gray-600" },

    // ========== ARCHIVES ==========
    zip: { icon: Archive, color: "text-yellow-600" },
    rar: { icon: Archive, color: "text-yellow-600" },
    "7z": { icon: Archive, color: "text-yellow-600" },
    tar: { icon: Archive, color: "text-yellow-600" },
    gz: { icon: Archive, color: "text-yellow-600" },
    bz2: { icon: Archive, color: "text-yellow-600" },
    xz: { icon: Archive, color: "text-yellow-600" },
    zst: { icon: Archive, color: "text-yellow-600" },
    zstd: { icon: Archive, color: "text-yellow-600" },
    lz: { icon: Archive, color: "text-yellow-600" },
    lzma: { icon: Archive, color: "text-yellow-600" },
    "tar.gz": { icon: Archive, color: "text-yellow-600" },
    "tar.xz": { icon: Archive, color: "text-yellow-600" },
    "tar.bz2": { icon: Archive, color: "text-yellow-600" },
    "tar.7z": { icon: Archive, color: "text-yellow-600" },
    "tar.zst": { icon: Archive, color: "text-yellow-600" },
    "tar.zstd": { icon: Archive, color: "text-yellow-600" },
    iso: { icon: Archive, color: "text-blue-600" },
    dmg: { icon: Archive, color: "text-gray-600" },
    pkg: { icon: Archive, color: "text-gray-600" },

    // ========== MEDIA ==========
    // Audio
    mp3: { icon: Music, color: "text-green-500" },
    wav: { icon: Music, color: "text-blue-500" },
    flac: { icon: Music, color: "text-purple-500" },
    aac: { icon: Music, color: "text-pink-500" },
    ogg: { icon: Music, color: "text-orange-500" },
    m4a: { icon: Music, color: "text-yellow-500" },
    wma: { icon: Music, color: "text-blue-600" },
    aiff: { icon: Music, color: "text-green-600" },
    
    // Video
    mp4: { icon: Video, color: "text-purple-500" },
    mov: { icon: Video, color: "text-blue-500" },
    avi: { icon: Video, color: "text-gray-600" },
    mkv: { icon: Video, color: "text-purple-600" },
    wmv: { icon: Video, color: "text-blue-600" },
    flv: { icon: Video, color: "text-red-500" },
    webm: { icon: Video, color: "text-orange-500" },
    m4v: { icon: Video, color: "text-yellow-500" },
    mpg: { icon: Video, color: "text-gray-600" },
    mpeg: { icon: Video, color: "text-gray-600" },
    "3gp": { icon: Video, color: "text-green-500" },
    ogv: { icon: Video, color: "text-orange-500" },
    
    // ========== DATABASES ==========
    db: { icon: Database, color: "text-blue-500" },
    sqlite: { icon: Database, color: "text-blue-600" },
    sqlite3: { icon: Database, color: "text-blue-600" },
    mdb: { icon: Database, color: "text-green-500" },
    accdb: { icon: Database, color: "text-green-600" },
    dbf: { icon: Database, color: "text-gray-600" },
    mdf: { icon: Database, color: "text-blue-700" },
    ndf: { icon: Database, color: "text-blue-700" },
    ldf: { icon: DatabaseBackup, color: "text-purple-500" },
    bak: { icon: DatabaseBackup, color: "text-gray-600" },
    dump: { icon: DatabaseBackup, color: "text-gray-600" },

    // ========== EXECUTABLES & SYSTEM ==========
    exe: { icon: Settings, color: "text-gray-500" },
    dll: { icon: Settings, color: "text-purple-500" },
    sys: { icon: Settings, color: "text-gray-600" },
    drv: { icon: Settings, color: "text-blue-600" },
    msi: { icon: Package, color: "text-orange-500" },
    apk: { icon: Smartphone, color: "text-green-500" },
    ipa: { icon: Smartphone, color: "text-gray-600" },
    app: { icon: Settings, color: "text-gray-600" },
    deb: { icon: Package, color: "text-red-500" },
    rpm: { icon: Package, color: "text-red-600" },
    
    // ========== CONFIGURATION FILES ==========
    ".env": { icon: Settings, color: "text-gray-500" },
    ".env.local": { icon: Settings, color: "text-gray-600" },
    ".env.production": { icon: Settings, color: "text-red-500" },
    ".env.development": { icon: Settings, color: "text-green-500" },
    ".env.test": { icon: Settings, color: "text-yellow-500" },
    ".gitignore": { icon: GitBranch, color: "text-gray-500" },
    ".gitattributes": { icon: GitBranch, color: "text-gray-500" },
    ".gitmodules": { icon: GitBranch, color: "text-gray-500" },
    ".git": { icon: GitBranch, color: "text-gray-500" },
    ".npmrc": { icon: Package, color: "text-red-500" },
    ".yarnrc": { icon: Package, color: "text-blue-500" },
    ".dockerignore": { icon: Package, color: "text-blue-400" },
    ".editorconfig": { icon: Settings, color: "text-gray-600" },
    ".prettierrc": { icon: Palette, color: "text-pink-500" },
    ".eslintrc": { icon: Code, color: "text-purple-500" },
    ".eslintrc.json": { icon: Code, color: "text-purple-500" },
    ".eslintrc.js": { icon: Code, color: "text-purple-500" },
    ".babelrc": { icon: Code, color: "text-yellow-500" },
    ".babelrc.json": { icon: Code, color: "text-yellow-500" },
    ".babelrc.js": { icon: Code, color: "text-yellow-500" },
    ".stylelintrc": { icon: Palette, color: "text-pink-500" },
    "tsconfig.json": { icon: FileCode, color: "text-blue-600" },
    "jsconfig.json": { icon: FileCode, color: "text-yellow-500" },
    "webpack.config.js": { icon: Settings, color: "text-blue-500" },
    "vite.config.js": { icon: Zap, color: "text-purple-500" },
    "vite.config.ts": { icon: Zap, color: "text-purple-500" },
    "rollup.config.js": { icon: Settings, color: "text-red-500" },
    "jest.config.js": { icon: TestTube, color: "text-red-500" },
    "jest.config.ts": { icon: TestTube, color: "text-red-500" },
    
    // ========== PACKAGE & DEPENDENCY FILES ==========
    "package.json": { icon: Package, color: "text-red-500" },
    "package-lock.json": { icon: Package, color: "text-red-600" },
    "yarn.lock": { icon: Package, color: "text-blue-500" },
    "pnpm-lock.yaml": { icon: Package, color: "text-yellow-500" },
    "composer.json": { icon: Package, color: "text-purple-500" },
    "composer.lock": { icon: Package, color: "text-purple-600" },
    "requirements.txt": { icon: Package, color: "text-green-500" },
    "Pipfile": { icon: Package, color: "text-green-600" },
    "Pipfile.lock": { icon: Package, color: "text-green-600" },
    "pyproject.toml": { icon: Package, color: "text-green-500" },
    "poetry.lock": { icon: Package, color: "text-green-600" },
    "Cargo.toml": { icon: Package, color: "text-orange-600" },
    "Cargo.lock": { icon: Package, color: "text-orange-600" },
    "go.mod": { icon: Package, color: "text-blue-500" },
    "go.sum": { icon: Package, color: "text-blue-600" },
    "Gemfile": { icon: Package, color: "text-red-500" },
    "Gemfile.lock": { icon: Package, color: "text-red-600" },
    "build.gradle": { icon: Package, color: "text-green-600" },
    "build.gradle.kts": { icon: Package, color: "text-green-600" },
    "pom.xml": { icon: Package, color: "text-red-500" },
    
    // ========== DOCKER & CONTAINERS ==========
    "Dockerfile": { icon: Package, color: "text-blue-500" },
    "docker-compose.yml": { icon: Package, color: "text-blue-400" },
    "docker-compose.yaml": { icon: Package, color: "text-blue-400" },
    ".dockerfile": { icon: Package, color: "text-blue-500" },
    "compose.yml": { icon: Package, color: "text-blue-400" },
    "compose.yaml": { icon: Package, color: "text-blue-400" },
    
    // ========== EMAIL & COMMUNICATION ==========
    eml: { icon: Mail, color: "text-blue-500" },
    msg: { icon: Mail, color: "text-blue-600" },
    pst: { icon: Mail, color: "text-gray-600" },
    ost: { icon: Mail, color: "text-gray-600" },
    vcf: { icon: Users, color: "text-green-500" },
    ics: { icon: Calendar, color: "text-red-500" },

    // ========== SECURITY & CERTIFICATES ==========
    pem: { icon: Lock, color: "text-green-600" },
    key: { icon: Key, color: "text-yellow-600" },
    crt: { icon: Shield, color: "text-green-500" },
    cer: { icon: Shield, color: "text-green-500" },
    p12: { icon: Lock, color: "text-yellow-600" },
    pfx: { icon: Lock, color: "text-yellow-600" },
    gpg: { icon: Lock, color: "text-blue-600" },
    asc: { icon: Lock, color: "text-blue-600" },

    // ========== FONTS ==========
    ttf: { icon: Type, color: "text-purple-500" },
    otf: { icon: Type, color: "text-purple-600" },
    woff: { icon: Type, color: "text-blue-500" },
    woff2: { icon: Type, color: "text-blue-600" },
    eot: { icon: Type, color: "text-gray-600" },

    // ========== VECTOR & DESIGN ==========
    fig: { icon: Palette, color: "text-purple-500" },
    sketch: { icon: Palette, color: "text-orange-500" },
    xd: { icon: Palette, color: "text-pink-500" },
    indd: { icon: Book, color: "text-red-500" },
    idml: { icon: Book, color: "text-red-500" },

    // ========== 3D & CAD ==========
    stl: { icon: Box, color: "text-gray-600" },
    obj: { icon: Box, color: "text-gray-600" },
    fbx: { icon: Box, color: "text-blue-500" },
    blend: { icon: Box, color: "text-orange-500" },
    max: { icon: Box, color: "text-red-500" },
    maya: { icon: Box, color: "text-green-500" },
    cad: { icon: Box, color: "text-blue-600" },
    dwg: { icon: Box, color: "text-blue-600" },
    dxf: { icon: Box, color: "text-green-600" },

    // ========== GIS & MAPPING ==========
    shp: { icon: Map, color: "text-green-500" },
    kml: { icon: Map, color: "text-green-600" },
    kmz: { icon: Map, color: "text-green-600" },
    gpx: { icon: Map, color: "text-blue-500" },
    geojson: { icon: Map, color: "text-green-400" },

    // ========== VIRTUALIZATION ==========
    vdi: { icon: HardDrive, color: "text-blue-500" },
    vmdk: { icon: HardDrive, color: "text-blue-600" },
    vhd: { icon: HardDrive, color: "text-blue-700" },
    vhdx: { icon: HardDrive, color: "text-blue-700" },
    ovf: { icon: HardDrive, color: "text-purple-500" },
    ova: { icon: HardDrive, color: "text-purple-600" },
    qcow2: { icon: HardDrive, color: "text-green-500" },

    // ========== NETWORK & INTERNET ==========
    url: { icon: Globe, color: "text-blue-500" },
    webloc: { icon: Globe, color: "text-blue-500" },
    asp: { icon: Globe, color: "text-blue-600" },
    aspx: { icon: Globe, color: "text-blue-600" },
    jsp: { icon: Globe, color: "text-red-500" },
    ftp: { icon: Network, color: "text-green-500" },
    ssh_config: { icon: Terminal, color: "text-gray-600" },
    rdp: { icon: Monitor, color: "text-blue-500" },
    vnc: { icon: Monitor, color: "text-purple-500" },

    // ========== LOGS ==========
    log: { icon: FileText, color: "text-gray-500" },
    err: { icon: FileText, color: "text-red-500" },
    out: { icon: FileText, color: "text-green-500" },

    // ========== BACKUP ==========
    old: { icon: DatabaseBackup, color: "text-gray-600" },
    tmp: { icon: DatabaseBackup, color: "text-gray-600" },
    temp: { icon: DatabaseBackup, color: "text-gray-600" },
    swp: { icon: DatabaseBackup, color: "text-gray-600" },

    // ========== MISC ==========
    ini: { icon: Settings, color: "text-gray-600" },
    cfg: { icon: Settings, color: "text-gray-600" },
    conf: { icon: Settings, color: "text-gray-600" },
    reg: { icon: Settings, color: "text-blue-600" },
    inf: { icon: Settings, color: "text-blue-600" },
    pages: { icon: FileText, color: "text-gray-600" },
    numbers: { icon: FileSpreadsheet, color: "text-green-500" },
    keynote: { icon: Presentation, color: "text-yellow-500" },
    pub: { icon: FileText, color: "text-purple-500" },
}

// Helper function to get file icon
export function getFileIcon(filename: string): FileIcon {
    const extension = filename.split('.').pop()?.toLowerCase() || ''
    const fullName = filename.toLowerCase()
    
    // Check for full file names first (like package.json)
    if (FILE_ICONS[fullName]) {
        return FILE_ICONS[fullName]
    }
    
    // Check for extension
    if (FILE_ICONS[extension]) {
        return FILE_ICONS[extension]
    }
    
    // Default icon
    return { icon: File, color: "text-gray-500" }
}

// Folder icons (if you want to add folder support)
export const FOLDER_ICONS: Record<string, FileIcon> = {
    node_modules: { icon: Folder, color: "text-green-600" },
    src: { icon: Folder, color: "text-blue-500" },
    dist: { icon: Folder, color: "text-purple-500" },
    build: { icon: Folder, color: "text-orange-500" },
    public: { icon: Folder, color: "text-green-500" },
    assets: { icon: Folder, color: "text-yellow-500" },
    images: { icon: Image, color: "text-blue-400" },
    docs: { icon: Book, color: "text-gray-600" },
    tests: { icon: TestTube, color: "text-red-500" },
    __tests__: { icon: TestTube, color: "text-red-500" },
    test: { icon: TestTube, color: "text-red-500" },
    migrations: { icon: Database, color: "text-blue-600" },
    seeds: { icon: Database, color: "text-green-600" },
    config: { icon: Settings, color: "text-gray-600" },
    ".git": { icon: GitBranch, color: "text-gray-500" },
    ".github": { icon: GitBranch, color: "text-gray-500" },
    ".vscode": { icon: Settings, color: "text-blue-500" },
    ".idea": { icon: Settings, color: "text-purple-500" },
}